### ISSUE TITLE
Is this right for the test configuration?

### ISSUE THREAD

**Issue by lDNAl** [whwu95/MVFNet#2]
Hi I noticed your great job for action recognition from AAAI 2021.
And I am trying to get the test results as yours on Kinetics400. After I have processed all the test videos to get the frames, I found that there is no annotation processing for kinetics400 test set up, neither in your configuration file.
Could you share the test annotation for Kinetics400 and explain why using validation for test?
https://github.com/whwu95/MVFNet/blob/ed336228ad88821ffe407a4355017acb416e4670/configs/MVFNet/K400/mvf_kinetics400_2d_rgb_r50_dense.py#L58
https://github.com/whwu95/MVFNet/blob/ed336228ad88821ffe407a4355017acb416e4670/configs/MVFNet/K400/mvf_kinetics400_2d_rgb_r50_dense.py#L145
```python
ann_file_test = 'datalist/kinetics400/val_ffmpeg_fps30.txt'
...
test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_root=data_root_val,
        pipeline=test_pipeline, 
        test_mode=True,
        modality='RGB',
        filename_tmpl='img_{:05}.jpg'    ))
```
Thanks a lot!

**Comment by whwu95** [comment]
Thank you for your attention. Please follow the [instruction](https://github.com/whwu95/MVFNet/blob/main/data_process/DATASETS.md) to generate the datalist.

**Comment by lDNAl** [comment]
Sorry, I missed the lmdb part. I thought mvf data processing would not use that module, but it tells about the test set up. Thanks!
